apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY | b64enc }}
