apiVersion: v1
kind: Service
metadata:
  name: {{ include "apache-s3-chart.fullname" . }}
  labels:
    {{- include "apache-s3-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: 30007
  selector:
    {{- include "apache-s3-chart.selectorLabels" . | nindent 4 }}
